// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package proto

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ReqRun struct {
	_tab flatbuffers.Table
}

func GetRootAsReqRun(buf []byte, offset flatbuffers.UOffsetT) *ReqRun {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ReqRun{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *ReqRun) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ReqRun) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ReqRun) Cmd() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func ReqRunStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func ReqRunAddCmd(builder *flatbuffers.Builder, cmd flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(cmd), 0)
}
func ReqRunEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
