// Code generated by protoc-gen-go. DO NOT EDIT.
// source: smash.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RunRequest struct {
	Cell                 int32    `protobuf:"varint,1,opt,name=cell,proto3" json:"cell,omitempty"`
	Cwd                  string   `protobuf:"bytes,2,opt,name=cwd,proto3" json:"cwd,omitempty"`
	Argv                 []string `protobuf:"bytes,3,rep,name=argv,proto3" json:"argv,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RunRequest) Reset()         { *m = RunRequest{} }
func (m *RunRequest) String() string { return proto.CompactTextString(m) }
func (*RunRequest) ProtoMessage()    {}
func (*RunRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_85c015dadfa1ff75, []int{0}
}

func (m *RunRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunRequest.Unmarshal(m, b)
}
func (m *RunRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunRequest.Marshal(b, m, deterministic)
}
func (m *RunRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunRequest.Merge(m, src)
}
func (m *RunRequest) XXX_Size() int {
	return xxx_messageInfo_RunRequest.Size(m)
}
func (m *RunRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RunRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RunRequest proto.InternalMessageInfo

func (m *RunRequest) GetCell() int32 {
	if m != nil {
		return m.Cell
	}
	return 0
}

func (m *RunRequest) GetCwd() string {
	if m != nil {
		return m.Cwd
	}
	return ""
}

func (m *RunRequest) GetArgv() []string {
	if m != nil {
		return m.Argv
	}
	return nil
}

type TermAttr struct {
	Fg                   int32    `protobuf:"varint,1,opt,name=fg,proto3" json:"fg,omitempty"`
	Bg                   int32    `protobuf:"varint,2,opt,name=bg,proto3" json:"bg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TermAttr) Reset()         { *m = TermAttr{} }
func (m *TermAttr) String() string { return proto.CompactTextString(m) }
func (*TermAttr) ProtoMessage()    {}
func (*TermAttr) Descriptor() ([]byte, []int) {
	return fileDescriptor_85c015dadfa1ff75, []int{1}
}

func (m *TermAttr) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TermAttr.Unmarshal(m, b)
}
func (m *TermAttr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TermAttr.Marshal(b, m, deterministic)
}
func (m *TermAttr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TermAttr.Merge(m, src)
}
func (m *TermAttr) XXX_Size() int {
	return xxx_messageInfo_TermAttr.Size(m)
}
func (m *TermAttr) XXX_DiscardUnknown() {
	xxx_messageInfo_TermAttr.DiscardUnknown(m)
}

var xxx_messageInfo_TermAttr proto.InternalMessageInfo

func (m *TermAttr) GetFg() int32 {
	if m != nil {
		return m.Fg
	}
	return 0
}

func (m *TermAttr) GetBg() int32 {
	if m != nil {
		return m.Bg
	}
	return 0
}

type TermText struct {
	Row                  int32            `protobuf:"varint,1,opt,name=row,proto3" json:"row,omitempty"`
	Spans                []*TermText_Span `protobuf:"bytes,2,rep,name=spans,proto3" json:"spans,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *TermText) Reset()         { *m = TermText{} }
func (m *TermText) String() string { return proto.CompactTextString(m) }
func (*TermText) ProtoMessage()    {}
func (*TermText) Descriptor() ([]byte, []int) {
	return fileDescriptor_85c015dadfa1ff75, []int{2}
}

func (m *TermText) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TermText.Unmarshal(m, b)
}
func (m *TermText) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TermText.Marshal(b, m, deterministic)
}
func (m *TermText) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TermText.Merge(m, src)
}
func (m *TermText) XXX_Size() int {
	return xxx_messageInfo_TermText.Size(m)
}
func (m *TermText) XXX_DiscardUnknown() {
	xxx_messageInfo_TermText.DiscardUnknown(m)
}

var xxx_messageInfo_TermText proto.InternalMessageInfo

func (m *TermText) GetRow() int32 {
	if m != nil {
		return m.Row
	}
	return 0
}

func (m *TermText) GetSpans() []*TermText_Span {
	if m != nil {
		return m.Spans
	}
	return nil
}

type TermText_Span struct {
	Attr                 *TermAttr `protobuf:"bytes,1,opt,name=attr,proto3" json:"attr,omitempty"`
	Text                 string    `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *TermText_Span) Reset()         { *m = TermText_Span{} }
func (m *TermText_Span) String() string { return proto.CompactTextString(m) }
func (*TermText_Span) ProtoMessage()    {}
func (*TermText_Span) Descriptor() ([]byte, []int) {
	return fileDescriptor_85c015dadfa1ff75, []int{2, 0}
}

func (m *TermText_Span) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TermText_Span.Unmarshal(m, b)
}
func (m *TermText_Span) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TermText_Span.Marshal(b, m, deterministic)
}
func (m *TermText_Span) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TermText_Span.Merge(m, src)
}
func (m *TermText_Span) XXX_Size() int {
	return xxx_messageInfo_TermText_Span.Size(m)
}
func (m *TermText_Span) XXX_DiscardUnknown() {
	xxx_messageInfo_TermText_Span.DiscardUnknown(m)
}

var xxx_messageInfo_TermText_Span proto.InternalMessageInfo

func (m *TermText_Span) GetAttr() *TermAttr {
	if m != nil {
		return m.Attr
	}
	return nil
}

func (m *TermText_Span) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type TermState struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TermState) Reset()         { *m = TermState{} }
func (m *TermState) String() string { return proto.CompactTextString(m) }
func (*TermState) ProtoMessage()    {}
func (*TermState) Descriptor() ([]byte, []int) {
	return fileDescriptor_85c015dadfa1ff75, []int{3}
}

func (m *TermState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TermState.Unmarshal(m, b)
}
func (m *TermState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TermState.Marshal(b, m, deterministic)
}
func (m *TermState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TermState.Merge(m, src)
}
func (m *TermState) XXX_Size() int {
	return xxx_messageInfo_TermState.Size(m)
}
func (m *TermState) XXX_DiscardUnknown() {
	xxx_messageInfo_TermState.DiscardUnknown(m)
}

var xxx_messageInfo_TermState proto.InternalMessageInfo

type Output struct {
	Cell int32 `protobuf:"varint,1,opt,name=cell,proto3" json:"cell,omitempty"`
	// Types that are valid to be assigned to Output:
	//	*Output_Error
	//	*Output_Text
	//	*Output_ExitCode
	Output               isOutput_Output `protobuf_oneof:"output"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Output) Reset()         { *m = Output{} }
func (m *Output) String() string { return proto.CompactTextString(m) }
func (*Output) ProtoMessage()    {}
func (*Output) Descriptor() ([]byte, []int) {
	return fileDescriptor_85c015dadfa1ff75, []int{4}
}

func (m *Output) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Output.Unmarshal(m, b)
}
func (m *Output) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Output.Marshal(b, m, deterministic)
}
func (m *Output) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Output.Merge(m, src)
}
func (m *Output) XXX_Size() int {
	return xxx_messageInfo_Output.Size(m)
}
func (m *Output) XXX_DiscardUnknown() {
	xxx_messageInfo_Output.DiscardUnknown(m)
}

var xxx_messageInfo_Output proto.InternalMessageInfo

func (m *Output) GetCell() int32 {
	if m != nil {
		return m.Cell
	}
	return 0
}

type isOutput_Output interface {
	isOutput_Output()
}

type Output_Error struct {
	Error string `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

type Output_Text struct {
	Text *TermText `protobuf:"bytes,3,opt,name=text,proto3,oneof"`
}

type Output_ExitCode struct {
	ExitCode int32 `protobuf:"varint,4,opt,name=exit_code,json=exitCode,proto3,oneof"`
}

func (*Output_Error) isOutput_Output() {}

func (*Output_Text) isOutput_Output() {}

func (*Output_ExitCode) isOutput_Output() {}

func (m *Output) GetOutput() isOutput_Output {
	if m != nil {
		return m.Output
	}
	return nil
}

func (m *Output) GetError() string {
	if x, ok := m.GetOutput().(*Output_Error); ok {
		return x.Error
	}
	return ""
}

func (m *Output) GetText() *TermText {
	if x, ok := m.GetOutput().(*Output_Text); ok {
		return x.Text
	}
	return nil
}

func (m *Output) GetExitCode() int32 {
	if x, ok := m.GetOutput().(*Output_ExitCode); ok {
		return x.ExitCode
	}
	return 0
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Output) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Output_Error)(nil),
		(*Output_Text)(nil),
		(*Output_ExitCode)(nil),
	}
}

type ServerMsg struct {
	// Types that are valid to be assigned to Msg:
	//	*ServerMsg_Output
	Msg                  isServerMsg_Msg `protobuf_oneof:"msg"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ServerMsg) Reset()         { *m = ServerMsg{} }
func (m *ServerMsg) String() string { return proto.CompactTextString(m) }
func (*ServerMsg) ProtoMessage()    {}
func (*ServerMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_85c015dadfa1ff75, []int{5}
}

func (m *ServerMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerMsg.Unmarshal(m, b)
}
func (m *ServerMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerMsg.Marshal(b, m, deterministic)
}
func (m *ServerMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerMsg.Merge(m, src)
}
func (m *ServerMsg) XXX_Size() int {
	return xxx_messageInfo_ServerMsg.Size(m)
}
func (m *ServerMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerMsg.DiscardUnknown(m)
}

var xxx_messageInfo_ServerMsg proto.InternalMessageInfo

type isServerMsg_Msg interface {
	isServerMsg_Msg()
}

type ServerMsg_Output struct {
	Output *Output `protobuf:"bytes,1,opt,name=output,proto3,oneof"`
}

func (*ServerMsg_Output) isServerMsg_Msg() {}

func (m *ServerMsg) GetMsg() isServerMsg_Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (m *ServerMsg) GetOutput() *Output {
	if x, ok := m.GetMsg().(*ServerMsg_Output); ok {
		return x.Output
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ServerMsg) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ServerMsg_Output)(nil),
	}
}

func init() {
	proto.RegisterType((*RunRequest)(nil), "proto.RunRequest")
	proto.RegisterType((*TermAttr)(nil), "proto.TermAttr")
	proto.RegisterType((*TermText)(nil), "proto.TermText")
	proto.RegisterType((*TermText_Span)(nil), "proto.TermText.Span")
	proto.RegisterType((*TermState)(nil), "proto.TermState")
	proto.RegisterType((*Output)(nil), "proto.Output")
	proto.RegisterType((*ServerMsg)(nil), "proto.ServerMsg")
}

func init() { proto.RegisterFile("smash.proto", fileDescriptor_85c015dadfa1ff75) }

var fileDescriptor_85c015dadfa1ff75 = []byte{
	// 326 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xcd, 0x4b, 0xf3, 0x40,
	0x10, 0xc6, 0xf3, 0x59, 0x9a, 0x09, 0xef, 0x07, 0xcb, 0xcb, 0x4b, 0x10, 0x84, 0x10, 0x11, 0x43,
	0x0f, 0x3d, 0xd4, 0xa3, 0x07, 0xb1, 0x82, 0xe4, 0x22, 0xc2, 0xb6, 0x77, 0x49, 0xdb, 0xe9, 0x2a,
	0xb4, 0xdd, 0xb8, 0x3b, 0x69, 0xfb, 0x07, 0x78, 0xf1, 0xbf, 0x96, 0xfd, 0x28, 0x08, 0x7a, 0xca,
	0x33, 0x3b, 0xcf, 0xfc, 0xe6, 0x99, 0x40, 0xae, 0xb7, 0xad, 0x7e, 0x19, 0x77, 0x4a, 0x92, 0x64,
	0xa9, 0xfd, 0x54, 0x0f, 0x00, 0xbc, 0xdf, 0x71, 0x7c, 0xeb, 0x51, 0x13, 0x63, 0x90, 0x2c, 0x71,
	0xb3, 0x29, 0xc2, 0x32, 0xac, 0x53, 0x6e, 0x35, 0xfb, 0x0b, 0xf1, 0xf2, 0xb0, 0x2a, 0xa2, 0x32,
	0xac, 0x33, 0x6e, 0xa4, 0x71, 0xb5, 0x4a, 0xec, 0x8b, 0xb8, 0x8c, 0xeb, 0x8c, 0x5b, 0x5d, 0x8d,
	0x60, 0x38, 0x47, 0xb5, 0xbd, 0x23, 0x52, 0xec, 0x37, 0x44, 0x6b, 0xe1, 0x19, 0xd1, 0x5a, 0x98,
	0x7a, 0x21, 0x2c, 0x20, 0xe5, 0xd1, 0x42, 0x54, 0x1f, 0xa1, 0x33, 0xcf, 0xf1, 0x48, 0x06, 0xaf,
	0xe4, 0xc1, 0xbb, 0x8d, 0x64, 0x23, 0x48, 0x75, 0xd7, 0xee, 0x74, 0x11, 0x95, 0x71, 0x9d, 0x4f,
	0xfe, 0xb9, 0xc0, 0xe3, 0xd3, 0xc4, 0x78, 0xd6, 0xb5, 0x3b, 0xee, 0x2c, 0x67, 0xb7, 0x90, 0x98,
	0x92, 0x5d, 0x40, 0xd2, 0x12, 0x29, 0x8b, 0xc9, 0x27, 0x7f, 0xbe, 0x8c, 0x98, 0x44, 0xdc, 0x36,
	0x4d, 0x6e, 0xc2, 0x23, 0xf9, 0x53, 0xac, 0xae, 0x72, 0xc8, 0x8c, 0x6b, 0x46, 0x2d, 0x61, 0xf5,
	0x1e, 0xc2, 0xe0, 0xa9, 0xa7, 0xae, 0xff, 0xf9, 0x4f, 0xfc, 0x87, 0x14, 0x95, 0x92, 0xca, 0x01,
	0x9a, 0x80, 0xbb, 0x92, 0x5d, 0x7a, 0x6e, 0xfc, 0x6d, 0xb9, 0xc9, 0xdb, 0x04, 0x6e, 0x15, 0x3b,
	0x87, 0x0c, 0x8f, 0xaf, 0xf4, 0xbc, 0x94, 0x2b, 0x2c, 0x12, 0xc3, 0x6d, 0x02, 0x3e, 0x34, 0x4f,
	0xf7, 0x72, 0x85, 0xd3, 0x21, 0x0c, 0xa4, 0xdd, 0x5d, 0xdd, 0x40, 0x36, 0x43, 0xb5, 0x47, 0xf5,
	0xa8, 0x05, 0xbb, 0x3a, 0x3d, 0xfb, 0xdb, 0x7e, 0x79, 0xbc, 0xcb, 0xd9, 0x04, 0xdc, 0xb7, 0xa7,
	0x29, 0xc4, 0x5b, 0x2d, 0x16, 0x03, 0xdb, 0xbe, 0xfe, 0x0c, 0x00, 0x00, 0xff, 0xff, 0x15, 0x99,
	0xf7, 0xa2, 0xed, 0x01, 0x00, 0x00,
}
