// generated by stringer -type=KeySym; DO NOT EDIT

package base

import "fmt"

const (
	_KeySym_name_0 = "KeyNone"
	_KeySym_name_1 = "KeyBackspaceKeyTabKeyNL"
	_KeySym_name_2 = "KeyCR"
	_KeySym_name_3 = "KeyLeftKeyRightKeyUpKeyDown"
)

var (
	_KeySym_index_0 = [...]uint8{0, 7}
	_KeySym_index_1 = [...]uint8{0, 12, 18, 23}
	_KeySym_index_2 = [...]uint8{0, 5}
	_KeySym_index_3 = [...]uint8{0, 7, 15, 20, 27}
)

func (i KeySym) String() string {
	switch {
	case i == 0:
		return _KeySym_name_0
	case 8 <= i && i <= 10:
		i -= 8
		return _KeySym_name_1[_KeySym_index_1[i]:_KeySym_index_1[i+1]]
	case i == 13:
		return _KeySym_name_2
	case 133 <= i && i <= 136:
		i -= 133
		return _KeySym_name_3[_KeySym_index_3[i]:_KeySym_index_3[i+1]]
	default:
		return fmt.Sprintf("KeySym(%d)", i)
	}
}
