// automatically generated by the FlatBuffers compiler, do not modify

/**
 * @constructor
 */
export namespace proto {
  export class ReqRun {
    bb: flatbuffers.ByteBuffer | null = null;

    bb_pos: number = 0;
    /**
     * @param number i
     * @param flatbuffers.ByteBuffer bb
     * @returns ReqRun
     */
    __init(i: number, bb: flatbuffers.ByteBuffer): ReqRun {
      this.bb_pos = i;
      this.bb = bb;
      return this;
    }

    /**
     * @param flatbuffers.ByteBuffer bb
     * @param ReqRun= obj
     * @returns ReqRun
     */
    static getRoot(bb: flatbuffers.ByteBuffer, obj?: ReqRun): ReqRun {
      return (obj || new ReqRun()).__init(
        bb.readInt32(bb.position()) + bb.position(),
        bb
      );
    }

    /**
     * @param flatbuffers.Encoding= optionalEncoding
     * @returns string|Uint8Array|null
     */
    cmd(): string | null;
    cmd(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    cmd(optionalEncoding?: any): string | Uint8Array | null {
      var offset = this.bb!.__offset(this.bb_pos, 4);
      return offset
        ? this.bb!.__string(this.bb_pos + offset, optionalEncoding)
        : null;
    }

    /**
     * @param flatbuffers.Builder builder
     */
    static start(builder: flatbuffers.Builder) {
      builder.startObject(1);
    }

    /**
     * @param flatbuffers.Builder builder
     * @param flatbuffers.Offset cmdOffset
     */
    static addCmd(builder: flatbuffers.Builder, cmdOffset: flatbuffers.Offset) {
      builder.addFieldOffset(0, cmdOffset, 0);
    }

    /**
     * @param flatbuffers.Builder builder
     * @returns flatbuffers.Offset
     */
    static end(builder: flatbuffers.Builder): flatbuffers.Offset {
      var offset = builder.endObject();
      return offset;
    }

    static create(
      builder: flatbuffers.Builder,
      cmdOffset: flatbuffers.Offset
    ): flatbuffers.Offset {
      ReqRun.start(builder);
      ReqRun.addCmd(builder, cmdOffset);
      return ReqRun.end(builder);
    }
  }
}
